/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

module alu_4bit(A, B, ALU_Sel, Result, Zero);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  input [3:0] A;
  wire [3:0] A;
  input [1:0] ALU_Sel;
  wire [1:0] ALU_Sel;
  input [3:0] B;
  wire [3:0] B;
  output [3:0] Result;
  wire [3:0] Result;
  output Zero;
  wire Zero;
  INVX1 _29_ (
    .A(ALU_Sel[1]),
    .Y(_00_)
  );
  NAND2X1 _30_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_01_)
  );
  OR2X1 _31_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_02_)
  );
  OAI21X1 _32_ (
    .A(ALU_Sel[0]),
    .B(_00_),
    .C(_02_),
    .Y(_03_)
  );
  MUX2X1 _33_ (
    .A(_03_),
    .B(_00_),
    .S(_01_),
    .Y(Result[0])
  );
  OAI21X1 _34_ (
    .A(ALU_Sel[0]),
    .B(B[1]),
    .C(A[1]),
    .Y(_04_)
  );
  MUX2X1 _35_ (
    .A(A[0]),
    .B(ALU_Sel[0]),
    .S(B[0]),
    .Y(_05_)
  );
  XOR2X1 _36_ (
    .A(ALU_Sel[0]),
    .B(B[1]),
    .Y(_06_)
  );
  NAND2X1 _37_ (
    .A(A[1]),
    .B(_06_),
    .Y(_07_)
  );
  XNOR2X1 _38_ (
    .A(A[1]),
    .B(_06_),
    .Y(_08_)
  );
  XNOR2X1 _39_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  AOI21X1 _40_ (
    .A(ALU_Sel[0]),
    .B(B[1]),
    .C(_00_),
    .Y(_10_)
  );
  AOI22X1 _41_ (
    .A(_00_),
    .B(_09_),
    .C(_10_),
    .D(_04_),
    .Y(Result[1])
  );
  NAND2X1 _42_ (
    .A(ALU_Sel[0]),
    .B(B[2]),
    .Y(_11_)
  );
  OR2X1 _43_ (
    .A(ALU_Sel[0]),
    .B(B[2]),
    .Y(_12_)
  );
  NAND2X1 _44_ (
    .A(A[2]),
    .B(_12_),
    .Y(_13_)
  );
  AND2X1 _45_ (
    .A(_11_),
    .B(_13_),
    .Y(_14_)
  );
  OAI21X1 _46_ (
    .A(_05_),
    .B(_08_),
    .C(_07_),
    .Y(_15_)
  );
  AOI21X1 _47_ (
    .A(ALU_Sel[0]),
    .B(B[2]),
    .C(_13_),
    .Y(_16_)
  );
  AOI21X1 _48_ (
    .A(_11_),
    .B(_12_),
    .C(A[2]),
    .Y(_17_)
  );
  INVX1 _49_ (
    .A(_17_),
    .Y(_18_)
  );
  OR2X1 _50_ (
    .A(_16_),
    .B(_17_),
    .Y(_19_)
  );
  XOR2X1 _51_ (
    .A(_15_),
    .B(_19_),
    .Y(_20_)
  );
  MUX2X1 _52_ (
    .A(_14_),
    .B(_20_),
    .S(ALU_Sel[1]),
    .Y(Result[2])
  );
  AOI21X1 _53_ (
    .A(_15_),
    .B(_18_),
    .C(_16_),
    .Y(_21_)
  );
  XOR2X1 _54_ (
    .A(ALU_Sel[0]),
    .B(B[3]),
    .Y(_22_)
  );
  AOI21X1 _55_ (
    .A(ALU_Sel[0]),
    .B(B[3]),
    .C(A[3]),
    .Y(_23_)
  );
  XNOR2X1 _56_ (
    .A(A[3]),
    .B(_22_),
    .Y(_24_)
  );
  XNOR2X1 _57_ (
    .A(_21_),
    .B(_24_),
    .Y(_25_)
  );
  OAI21X1 _58_ (
    .A(ALU_Sel[0]),
    .B(B[3]),
    .C(ALU_Sel[1]),
    .Y(_26_)
  );
  OR2X1 _59_ (
    .A(_23_),
    .B(_26_),
    .Y(_27_)
  );
  OAI21X1 _60_ (
    .A(ALU_Sel[1]),
    .B(_25_),
    .C(_27_),
    .Y(Result[3])
  );
  OR2X1 _61_ (
    .A(Result[0]),
    .B(Result[1]),
    .Y(_28_)
  );
  NOR3X1 _62_ (
    .A(Result[2]),
    .B(Result[3]),
    .C(_28_),
    .Y(Zero)
  );
endmodule
