/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

module alu_4bit(clk, rst, A, B, ALU_Sel, Result, Zero);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire [3:0] _083_;
  wire _084_;
  input [3:0] A;
  wire [3:0] A;
  input [1:0] ALU_Sel;
  wire [1:0] ALU_Sel;
  wire [1:0] ALU_Sel_ff;
  wire [3:0] A_ff;
  input [3:0] B;
  wire [3:0] B;
  wire [3:0] B_ff;
  wire [3:0] B_for_add_sub;
  output [3:0] Result;
  wire [3:0] Result;
  wire [3:0] Result_ff;
  output Zero;
  wire Zero;
  wire Zero_ff;
  wire [3:0] and_result;
  wire carry_in;
  wire carry_out_sub;
  wire carry_out_sum;
  input clk;
  wire clk;
  wire [3:0] \dff_A.q ;
  wire [1:0] \dff_ALU_Sel.q ;
  wire [3:0] \dff_B.q ;
  wire [3:0] \dff_Result.q ;
  wire [0:0] \dff_Zero.q ;
  wire [3:0] or_result;
  input rst;
  wire rst;
  wire [3:0] sub_result;
  wire [3:0] sum_result;
  INVX1 _085_ (
    .A(_033_),
    .Y(_038_)
  );
  INVX1 _086_ (
    .A(_063_),
    .Y(_013_)
  );
  NAND2X1 _087_ (
    .A(_034_),
    .B(_028_),
    .Y(_039_)
  );
  INVX1 _088_ (
    .A(_039_),
    .Y(_009_)
  );
  OR2X1 _089_ (
    .A(_034_),
    .B(_028_),
    .Y(_059_)
  );
  AND2X1 _090_ (
    .A(_039_),
    .B(_059_),
    .Y(_064_)
  );
  OAI21X1 _091_ (
    .A(_032_),
    .B(_038_),
    .C(_064_),
    .Y(_040_)
  );
  OAI21X1 _092_ (
    .A(_038_),
    .B(_039_),
    .C(_040_),
    .Y(_004_)
  );
  XOR2X1 _093_ (
    .A(_032_),
    .B(_035_),
    .Y(_001_)
  );
  NAND2X1 _094_ (
    .A(_029_),
    .B(_001_),
    .Y(_041_)
  );
  NOR2X1 _095_ (
    .A(_029_),
    .B(_001_),
    .Y(_042_)
  );
  XOR2X1 _096_ (
    .A(_029_),
    .B(_001_),
    .Y(_043_)
  );
  MUX2X1 _097_ (
    .A(_028_),
    .B(_032_),
    .S(_034_),
    .Y(_044_)
  );
  XNOR2X1 _098_ (
    .A(_043_),
    .B(_044_),
    .Y(_065_)
  );
  AND2X1 _099_ (
    .A(_029_),
    .B(_035_),
    .Y(_010_)
  );
  OR2X1 _100_ (
    .A(_029_),
    .B(_035_),
    .Y(_060_)
  );
  AOI21X1 _101_ (
    .A(_032_),
    .B(_060_),
    .C(_010_),
    .Y(_045_)
  );
  NAND2X1 _102_ (
    .A(_038_),
    .B(_065_),
    .Y(_046_)
  );
  OAI21X1 _103_ (
    .A(_038_),
    .B(_045_),
    .C(_046_),
    .Y(_005_)
  );
  OAI21X1 _104_ (
    .A(_042_),
    .B(_044_),
    .C(_041_),
    .Y(_047_)
  );
  XOR2X1 _105_ (
    .A(_032_),
    .B(_036_),
    .Y(_002_)
  );
  AND2X1 _106_ (
    .A(_030_),
    .B(_002_),
    .Y(_048_)
  );
  NAND2X1 _107_ (
    .A(_030_),
    .B(_002_),
    .Y(_049_)
  );
  OR2X1 _108_ (
    .A(_030_),
    .B(_002_),
    .Y(_050_)
  );
  NAND2X1 _109_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  XOR2X1 _110_ (
    .A(_047_),
    .B(_051_),
    .Y(_052_)
  );
  INVX1 _111_ (
    .A(_052_),
    .Y(_066_)
  );
  AND2X1 _112_ (
    .A(_030_),
    .B(_036_),
    .Y(_011_)
  );
  OR2X1 _113_ (
    .A(_030_),
    .B(_036_),
    .Y(_061_)
  );
  AOI21X1 _114_ (
    .A(_032_),
    .B(_061_),
    .C(_011_),
    .Y(_053_)
  );
  MUX2X1 _115_ (
    .A(_052_),
    .B(_053_),
    .S(_038_),
    .Y(_006_)
  );
  AOI21X1 _116_ (
    .A(_047_),
    .B(_050_),
    .C(_048_),
    .Y(_054_)
  );
  XOR2X1 _117_ (
    .A(_032_),
    .B(_037_),
    .Y(_003_)
  );
  XNOR2X1 _118_ (
    .A(_031_),
    .B(_003_),
    .Y(_055_)
  );
  XNOR2X1 _119_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  INVX1 _120_ (
    .A(_056_),
    .Y(_067_)
  );
  AND2X1 _121_ (
    .A(_037_),
    .B(_031_),
    .Y(_012_)
  );
  OR2X1 _122_ (
    .A(_037_),
    .B(_031_),
    .Y(_062_)
  );
  AOI21X1 _123_ (
    .A(_032_),
    .B(_062_),
    .C(_012_),
    .Y(_057_)
  );
  MUX2X1 _124_ (
    .A(_056_),
    .B(_057_),
    .S(_038_),
    .Y(_007_)
  );
  OR2X1 _125_ (
    .A(_004_),
    .B(_006_),
    .Y(_058_)
  );
  NOR3X1 _126_ (
    .A(_005_),
    .B(_007_),
    .C(_058_),
    .Y(_008_)
  );
  XOR2X1 _127_ (
    .A(_032_),
    .B(_034_),
    .Y(_000_)
  );
  INVX1 _128_ (
    .A(_063_),
    .Y(_014_)
  );
  INVX1 _129_ (
    .A(_063_),
    .Y(_015_)
  );
  INVX1 _130_ (
    .A(_063_),
    .Y(_016_)
  );
  INVX1 _131_ (
    .A(_063_),
    .Y(_017_)
  );
  INVX1 _132_ (
    .A(_063_),
    .Y(_018_)
  );
  INVX1 _133_ (
    .A(_063_),
    .Y(_019_)
  );
  INVX1 _134_ (
    .A(_063_),
    .Y(_020_)
  );
  INVX1 _135_ (
    .A(_063_),
    .Y(_021_)
  );
  INVX1 _136_ (
    .A(_063_),
    .Y(_022_)
  );
  INVX1 _137_ (
    .A(_063_),
    .Y(_023_)
  );
  INVX1 _138_ (
    .A(_063_),
    .Y(_024_)
  );
  INVX1 _139_ (
    .A(_063_),
    .Y(_025_)
  );
  INVX1 _140_ (
    .A(_063_),
    .Y(_026_)
  );
  INVX1 _141_ (
    .A(_063_),
    .Y(_027_)
  );
  BUFX2 _142_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(ALU_Sel_ff[0])
  );
  BUFX2 _143_ (
    .A(\dff_ALU_Sel.q [1]),
    .Y(ALU_Sel_ff[1])
  );
  BUFX2 _144_ (
    .A(\dff_A.q [0]),
    .Y(A_ff[0])
  );
  BUFX2 _145_ (
    .A(\dff_A.q [1]),
    .Y(A_ff[1])
  );
  BUFX2 _146_ (
    .A(\dff_A.q [2]),
    .Y(A_ff[2])
  );
  BUFX2 _147_ (
    .A(\dff_A.q [3]),
    .Y(A_ff[3])
  );
  BUFX2 _148_ (
    .A(\dff_B.q [0]),
    .Y(B_ff[0])
  );
  BUFX2 _149_ (
    .A(\dff_B.q [1]),
    .Y(B_ff[1])
  );
  BUFX2 _150_ (
    .A(\dff_B.q [2]),
    .Y(B_ff[2])
  );
  BUFX2 _151_ (
    .A(\dff_B.q [3]),
    .Y(B_ff[3])
  );
  BUFX2 _152_ (
    .A(\dff_Result.q [0]),
    .Y(_083_[0])
  );
  BUFX2 _153_ (
    .A(\dff_Result.q [1]),
    .Y(_083_[1])
  );
  BUFX2 _154_ (
    .A(\dff_Result.q [2]),
    .Y(_083_[2])
  );
  BUFX2 _155_ (
    .A(\dff_Result.q [3]),
    .Y(_083_[3])
  );
  BUFX2 _156_ (
    .A(\dff_Zero.q ),
    .Y(_084_)
  );
  BUFX2 _157_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(carry_in)
  );
  BUFX2 _158_ (
    .A(1'hx),
    .Y(carry_out_sub)
  );
  BUFX2 _159_ (
    .A(1'hx),
    .Y(carry_out_sum)
  );
  BUFX2 _160_ (
    .A(sub_result[0]),
    .Y(sum_result[0])
  );
  BUFX2 _161_ (
    .A(sub_result[1]),
    .Y(sum_result[1])
  );
  BUFX2 _162_ (
    .A(sub_result[2]),
    .Y(sum_result[2])
  );
  BUFX2 _163_ (
    .A(sub_result[3]),
    .Y(sum_result[3])
  );
  BUFX2 _164_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(_032_)
  );
  BUFX2 _165_ (
    .A(\dff_B.q [0]),
    .Y(_034_)
  );
  BUFX2 _166_ (
    .A(\dff_A.q [0]),
    .Y(_028_)
  );
  BUFX2 _167_ (
    .A(_064_),
    .Y(sub_result[0])
  );
  BUFX2 _168_ (
    .A(\dff_ALU_Sel.q [1]),
    .Y(_033_)
  );
  BUFX2 _169_ (
    .A(_009_),
    .Y(and_result[0])
  );
  BUFX2 _170_ (
    .A(_059_),
    .Y(or_result[0])
  );
  BUFX2 _171_ (
    .A(_004_),
    .Y(Result_ff[0])
  );
  BUFX2 _172_ (
    .A(\dff_A.q [1]),
    .Y(_029_)
  );
  BUFX2 _173_ (
    .A(\dff_B.q [1]),
    .Y(_035_)
  );
  BUFX2 _174_ (
    .A(_065_),
    .Y(sub_result[1])
  );
  BUFX2 _175_ (
    .A(_010_),
    .Y(and_result[1])
  );
  BUFX2 _176_ (
    .A(_060_),
    .Y(or_result[1])
  );
  BUFX2 _177_ (
    .A(_005_),
    .Y(Result_ff[1])
  );
  BUFX2 _178_ (
    .A(\dff_A.q [2]),
    .Y(_030_)
  );
  BUFX2 _179_ (
    .A(\dff_B.q [2]),
    .Y(_036_)
  );
  BUFX2 _180_ (
    .A(_066_),
    .Y(sub_result[2])
  );
  BUFX2 _181_ (
    .A(_011_),
    .Y(and_result[2])
  );
  BUFX2 _182_ (
    .A(_061_),
    .Y(or_result[2])
  );
  BUFX2 _183_ (
    .A(_006_),
    .Y(Result_ff[2])
  );
  BUFX2 _184_ (
    .A(\dff_B.q [3]),
    .Y(_037_)
  );
  BUFX2 _185_ (
    .A(\dff_A.q [3]),
    .Y(_031_)
  );
  BUFX2 _186_ (
    .A(_067_),
    .Y(sub_result[3])
  );
  BUFX2 _187_ (
    .A(_012_),
    .Y(and_result[3])
  );
  BUFX2 _188_ (
    .A(_062_),
    .Y(or_result[3])
  );
  BUFX2 _189_ (
    .A(_007_),
    .Y(Result_ff[3])
  );
  BUFX2 _190_ (
    .A(_008_),
    .Y(Zero_ff)
  );
  BUFX2 _191_ (
    .A(_000_),
    .Y(B_for_add_sub[0])
  );
  BUFX2 _192_ (
    .A(_001_),
    .Y(B_for_add_sub[1])
  );
  BUFX2 _193_ (
    .A(_002_),
    .Y(B_for_add_sub[2])
  );
  BUFX2 _194_ (
    .A(_003_),
    .Y(B_for_add_sub[3])
  );
  BUFX2 _195_ (
    .A(rst),
    .Y(_063_)
  );
  BUFX2 _196_ (
    .A(_013_),
    .Y(_068_)
  );
  BUFX2 _197_ (
    .A(_014_),
    .Y(_069_)
  );
  BUFX2 _198_ (
    .A(_015_),
    .Y(_070_)
  );
  BUFX2 _199_ (
    .A(_016_),
    .Y(_071_)
  );
  BUFX2 _200_ (
    .A(_017_),
    .Y(_072_)
  );
  BUFX2 _201_ (
    .A(_018_),
    .Y(_073_)
  );
  BUFX2 _202_ (
    .A(_019_),
    .Y(_074_)
  );
  BUFX2 _203_ (
    .A(_020_),
    .Y(_075_)
  );
  BUFX2 _204_ (
    .A(_021_),
    .Y(_076_)
  );
  BUFX2 _205_ (
    .A(_022_),
    .Y(_077_)
  );
  BUFX2 _206_ (
    .A(_023_),
    .Y(_078_)
  );
  BUFX2 _207_ (
    .A(_024_),
    .Y(_079_)
  );
  BUFX2 _208_ (
    .A(_025_),
    .Y(_080_)
  );
  BUFX2 _209_ (
    .A(_026_),
    .Y(_081_)
  );
  BUFX2 _210_ (
    .A(_027_),
    .Y(_082_)
  );
  DFFSR _211_ (
    .CLK(clk),
    .D(A[0]),
    .Q(\dff_A.q [0]),
    .R(_068_),
    .S(1'h1)
  );
  DFFSR _212_ (
    .CLK(clk),
    .D(A[1]),
    .Q(\dff_A.q [1]),
    .R(_069_),
    .S(1'h1)
  );
  DFFSR _213_ (
    .CLK(clk),
    .D(A[2]),
    .Q(\dff_A.q [2]),
    .R(_070_),
    .S(1'h1)
  );
  DFFSR _214_ (
    .CLK(clk),
    .D(A[3]),
    .Q(\dff_A.q [3]),
    .R(_071_),
    .S(1'h1)
  );
  DFFSR _215_ (
    .CLK(clk),
    .D(ALU_Sel[0]),
    .Q(\dff_ALU_Sel.q [0]),
    .R(_072_),
    .S(1'h1)
  );
  DFFSR _216_ (
    .CLK(clk),
    .D(ALU_Sel[1]),
    .Q(\dff_ALU_Sel.q [1]),
    .R(_073_),
    .S(1'h1)
  );
  DFFSR _217_ (
    .CLK(clk),
    .D(B[0]),
    .Q(\dff_B.q [0]),
    .R(_074_),
    .S(1'h1)
  );
  DFFSR _218_ (
    .CLK(clk),
    .D(B[1]),
    .Q(\dff_B.q [1]),
    .R(_075_),
    .S(1'h1)
  );
  DFFSR _219_ (
    .CLK(clk),
    .D(B[2]),
    .Q(\dff_B.q [2]),
    .R(_076_),
    .S(1'h1)
  );
  DFFSR _220_ (
    .CLK(clk),
    .D(B[3]),
    .Q(\dff_B.q [3]),
    .R(_077_),
    .S(1'h1)
  );
  DFFSR _221_ (
    .CLK(clk),
    .D(Result_ff[0]),
    .Q(\dff_Result.q [0]),
    .R(_078_),
    .S(1'h1)
  );
  DFFSR _222_ (
    .CLK(clk),
    .D(Result_ff[1]),
    .Q(\dff_Result.q [1]),
    .R(_079_),
    .S(1'h1)
  );
  DFFSR _223_ (
    .CLK(clk),
    .D(Result_ff[2]),
    .Q(\dff_Result.q [2]),
    .R(_080_),
    .S(1'h1)
  );
  DFFSR _224_ (
    .CLK(clk),
    .D(Result_ff[3]),
    .Q(\dff_Result.q [3]),
    .R(_081_),
    .S(1'h1)
  );
  DFFSR _225_ (
    .CLK(clk),
    .D(Zero_ff),
    .Q(\dff_Zero.q ),
    .R(_082_),
    .S(1'h1)
  );
  BUFX4 _226_ (
    .A(_083_[0]),
    .Y(Result[0])
  );
  BUFX4 _227_ (
    .A(_083_[1]),
    .Y(Result[1])
  );
  BUFX4 _228_ (
    .A(_083_[2]),
    .Y(Result[2])
  );
  BUFX4 _229_ (
    .A(_083_[3]),
    .Y(Result[3])
  );
  BUFX4 _230_ (
    .A(_084_),
    .Y(Zero)
  );
endmodule
