/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

module alu_4bit(clk, rst_n, A, B, ALU_Sel, Result, Zero);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [3:0] _054_;
  wire _055_;
  input [3:0] A;
  wire [3:0] A;
  input [1:0] ALU_Sel;
  wire [1:0] ALU_Sel;
  wire [1:0] ALU_Sel_ff;
  wire [3:0] A_ff;
  input [3:0] B;
  wire [3:0] B;
  wire [3:0] B_ff;
  wire [3:0] B_for_add_sub;
  output [3:0] Result;
  wire [3:0] Result;
  wire [3:0] Result_ff;
  output Zero;
  wire Zero;
  wire Zero_ff;
  wire [3:0] and_result;
  wire carry_in;
  wire carry_out_sub;
  wire carry_out_sum;
  input clk;
  wire clk;
  wire [3:0] \dff_A.q ;
  wire [1:0] \dff_ALU_Sel.q ;
  wire [3:0] \dff_B.q ;
  wire [3:0] \dff_Result.q ;
  wire [0:0] \dff_Zero.q ;
  wire [3:0] or_result;
  input rst_n;
  wire rst_n;
  wire [3:0] sub_result;
  wire [3:0] sum_result;
  INVX1 _056_ (
    .A(_018_),
    .Y(_023_)
  );
  NAND2X1 _057_ (
    .A(_019_),
    .B(_013_),
    .Y(_024_)
  );
  INVX1 _058_ (
    .A(_024_),
    .Y(_009_)
  );
  OR2X1 _059_ (
    .A(_019_),
    .B(_013_),
    .Y(_046_)
  );
  AND2X1 _060_ (
    .A(_024_),
    .B(_046_),
    .Y(_050_)
  );
  OAI21X1 _061_ (
    .A(_017_),
    .B(_023_),
    .C(_050_),
    .Y(_025_)
  );
  OAI21X1 _062_ (
    .A(_023_),
    .B(_024_),
    .C(_025_),
    .Y(_004_)
  );
  XOR2X1 _063_ (
    .A(_017_),
    .B(_020_),
    .Y(_001_)
  );
  NAND2X1 _064_ (
    .A(_014_),
    .B(_001_),
    .Y(_026_)
  );
  NOR2X1 _065_ (
    .A(_014_),
    .B(_001_),
    .Y(_027_)
  );
  XOR2X1 _066_ (
    .A(_014_),
    .B(_001_),
    .Y(_028_)
  );
  MUX2X1 _067_ (
    .A(_013_),
    .B(_017_),
    .S(_019_),
    .Y(_029_)
  );
  XNOR2X1 _068_ (
    .A(_028_),
    .B(_029_),
    .Y(_051_)
  );
  NAND2X1 _069_ (
    .A(_014_),
    .B(_020_),
    .Y(_030_)
  );
  INVX1 _070_ (
    .A(_030_),
    .Y(_010_)
  );
  OR2X1 _071_ (
    .A(_014_),
    .B(_020_),
    .Y(_047_)
  );
  NAND2X1 _072_ (
    .A(_017_),
    .B(_047_),
    .Y(_031_)
  );
  OR2X1 _073_ (
    .A(_018_),
    .B(_051_),
    .Y(_032_)
  );
  NAND3X1 _074_ (
    .A(_018_),
    .B(_030_),
    .C(_031_),
    .Y(_033_)
  );
  AND2X1 _075_ (
    .A(_032_),
    .B(_033_),
    .Y(_005_)
  );
  OAI21X1 _076_ (
    .A(_027_),
    .B(_029_),
    .C(_026_),
    .Y(_034_)
  );
  XOR2X1 _077_ (
    .A(_017_),
    .B(_021_),
    .Y(_002_)
  );
  AND2X1 _078_ (
    .A(_015_),
    .B(_002_),
    .Y(_035_)
  );
  NAND2X1 _079_ (
    .A(_015_),
    .B(_002_),
    .Y(_036_)
  );
  OR2X1 _080_ (
    .A(_015_),
    .B(_002_),
    .Y(_037_)
  );
  NAND2X1 _081_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  XNOR2X1 _082_ (
    .A(_034_),
    .B(_038_),
    .Y(_052_)
  );
  AND2X1 _083_ (
    .A(_015_),
    .B(_021_),
    .Y(_011_)
  );
  OR2X1 _084_ (
    .A(_015_),
    .B(_021_),
    .Y(_048_)
  );
  AOI21X1 _085_ (
    .A(_017_),
    .B(_048_),
    .C(_011_),
    .Y(_039_)
  );
  NAND2X1 _086_ (
    .A(_023_),
    .B(_052_),
    .Y(_040_)
  );
  OAI21X1 _087_ (
    .A(_023_),
    .B(_039_),
    .C(_040_),
    .Y(_006_)
  );
  AOI21X1 _088_ (
    .A(_034_),
    .B(_037_),
    .C(_035_),
    .Y(_041_)
  );
  XOR2X1 _089_ (
    .A(_017_),
    .B(_022_),
    .Y(_003_)
  );
  XNOR2X1 _090_ (
    .A(_016_),
    .B(_003_),
    .Y(_042_)
  );
  XNOR2X1 _091_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  INVX1 _092_ (
    .A(_043_),
    .Y(_053_)
  );
  AND2X1 _093_ (
    .A(_022_),
    .B(_016_),
    .Y(_012_)
  );
  OR2X1 _094_ (
    .A(_022_),
    .B(_016_),
    .Y(_049_)
  );
  AOI21X1 _095_ (
    .A(_017_),
    .B(_049_),
    .C(_012_),
    .Y(_044_)
  );
  MUX2X1 _096_ (
    .A(_043_),
    .B(_044_),
    .S(_023_),
    .Y(_007_)
  );
  OR2X1 _097_ (
    .A(_004_),
    .B(_005_),
    .Y(_045_)
  );
  NOR3X1 _098_ (
    .A(_006_),
    .B(_007_),
    .C(_045_),
    .Y(_008_)
  );
  XOR2X1 _099_ (
    .A(_019_),
    .B(_017_),
    .Y(_000_)
  );
  BUFX2 _100_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(ALU_Sel_ff[0])
  );
  BUFX2 _101_ (
    .A(\dff_ALU_Sel.q [1]),
    .Y(ALU_Sel_ff[1])
  );
  BUFX2 _102_ (
    .A(\dff_A.q [0]),
    .Y(A_ff[0])
  );
  BUFX2 _103_ (
    .A(\dff_A.q [1]),
    .Y(A_ff[1])
  );
  BUFX2 _104_ (
    .A(\dff_A.q [2]),
    .Y(A_ff[2])
  );
  BUFX2 _105_ (
    .A(\dff_A.q [3]),
    .Y(A_ff[3])
  );
  BUFX2 _106_ (
    .A(\dff_B.q [0]),
    .Y(B_ff[0])
  );
  BUFX2 _107_ (
    .A(\dff_B.q [1]),
    .Y(B_ff[1])
  );
  BUFX2 _108_ (
    .A(\dff_B.q [2]),
    .Y(B_ff[2])
  );
  BUFX2 _109_ (
    .A(\dff_B.q [3]),
    .Y(B_ff[3])
  );
  BUFX2 _110_ (
    .A(\dff_Result.q [0]),
    .Y(_054_[0])
  );
  BUFX2 _111_ (
    .A(\dff_Result.q [1]),
    .Y(_054_[1])
  );
  BUFX2 _112_ (
    .A(\dff_Result.q [2]),
    .Y(_054_[2])
  );
  BUFX2 _113_ (
    .A(\dff_Result.q [3]),
    .Y(_054_[3])
  );
  BUFX2 _114_ (
    .A(\dff_Zero.q ),
    .Y(_055_)
  );
  BUFX2 _115_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(carry_in)
  );
  BUFX2 _116_ (
    .A(1'hx),
    .Y(carry_out_sub)
  );
  BUFX2 _117_ (
    .A(1'hx),
    .Y(carry_out_sum)
  );
  BUFX2 _118_ (
    .A(sub_result[0]),
    .Y(sum_result[0])
  );
  BUFX2 _119_ (
    .A(sub_result[1]),
    .Y(sum_result[1])
  );
  BUFX2 _120_ (
    .A(sub_result[2]),
    .Y(sum_result[2])
  );
  BUFX2 _121_ (
    .A(sub_result[3]),
    .Y(sum_result[3])
  );
  BUFX2 _122_ (
    .A(\dff_B.q [0]),
    .Y(_019_)
  );
  BUFX2 _123_ (
    .A(\dff_ALU_Sel.q [0]),
    .Y(_017_)
  );
  BUFX2 _124_ (
    .A(\dff_A.q [0]),
    .Y(_013_)
  );
  BUFX2 _125_ (
    .A(_050_),
    .Y(sub_result[0])
  );
  BUFX2 _126_ (
    .A(\dff_ALU_Sel.q [1]),
    .Y(_018_)
  );
  BUFX2 _127_ (
    .A(_009_),
    .Y(and_result[0])
  );
  BUFX2 _128_ (
    .A(_046_),
    .Y(or_result[0])
  );
  BUFX2 _129_ (
    .A(_004_),
    .Y(Result_ff[0])
  );
  BUFX2 _130_ (
    .A(\dff_A.q [1]),
    .Y(_014_)
  );
  BUFX2 _131_ (
    .A(\dff_B.q [1]),
    .Y(_020_)
  );
  BUFX2 _132_ (
    .A(_051_),
    .Y(sub_result[1])
  );
  BUFX2 _133_ (
    .A(_010_),
    .Y(and_result[1])
  );
  BUFX2 _134_ (
    .A(_047_),
    .Y(or_result[1])
  );
  BUFX2 _135_ (
    .A(_005_),
    .Y(Result_ff[1])
  );
  BUFX2 _136_ (
    .A(\dff_A.q [2]),
    .Y(_015_)
  );
  BUFX2 _137_ (
    .A(\dff_B.q [2]),
    .Y(_021_)
  );
  BUFX2 _138_ (
    .A(_052_),
    .Y(sub_result[2])
  );
  BUFX2 _139_ (
    .A(_011_),
    .Y(and_result[2])
  );
  BUFX2 _140_ (
    .A(_048_),
    .Y(or_result[2])
  );
  BUFX2 _141_ (
    .A(_006_),
    .Y(Result_ff[2])
  );
  BUFX2 _142_ (
    .A(\dff_B.q [3]),
    .Y(_022_)
  );
  BUFX2 _143_ (
    .A(\dff_A.q [3]),
    .Y(_016_)
  );
  BUFX2 _144_ (
    .A(_053_),
    .Y(sub_result[3])
  );
  BUFX2 _145_ (
    .A(_012_),
    .Y(and_result[3])
  );
  BUFX2 _146_ (
    .A(_049_),
    .Y(or_result[3])
  );
  BUFX2 _147_ (
    .A(_007_),
    .Y(Result_ff[3])
  );
  BUFX2 _148_ (
    .A(_008_),
    .Y(Zero_ff)
  );
  BUFX2 _149_ (
    .A(_000_),
    .Y(B_for_add_sub[0])
  );
  BUFX2 _150_ (
    .A(_001_),
    .Y(B_for_add_sub[1])
  );
  BUFX2 _151_ (
    .A(_002_),
    .Y(B_for_add_sub[2])
  );
  BUFX2 _152_ (
    .A(_003_),
    .Y(B_for_add_sub[3])
  );
  DFFSR _153_ (
    .CLK(clk),
    .D(A[0]),
    .Q(\dff_A.q [0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _154_ (
    .CLK(clk),
    .D(A[1]),
    .Q(\dff_A.q [1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _155_ (
    .CLK(clk),
    .D(A[2]),
    .Q(\dff_A.q [2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _156_ (
    .CLK(clk),
    .D(A[3]),
    .Q(\dff_A.q [3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _157_ (
    .CLK(clk),
    .D(ALU_Sel[0]),
    .Q(\dff_ALU_Sel.q [0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _158_ (
    .CLK(clk),
    .D(ALU_Sel[1]),
    .Q(\dff_ALU_Sel.q [1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _159_ (
    .CLK(clk),
    .D(B[0]),
    .Q(\dff_B.q [0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _160_ (
    .CLK(clk),
    .D(B[1]),
    .Q(\dff_B.q [1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _161_ (
    .CLK(clk),
    .D(B[2]),
    .Q(\dff_B.q [2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _162_ (
    .CLK(clk),
    .D(B[3]),
    .Q(\dff_B.q [3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _163_ (
    .CLK(clk),
    .D(Result_ff[0]),
    .Q(\dff_Result.q [0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _164_ (
    .CLK(clk),
    .D(Result_ff[1]),
    .Q(\dff_Result.q [1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _165_ (
    .CLK(clk),
    .D(Result_ff[2]),
    .Q(\dff_Result.q [2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _166_ (
    .CLK(clk),
    .D(Result_ff[3]),
    .Q(\dff_Result.q [3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _167_ (
    .CLK(clk),
    .D(Zero_ff),
    .Q(\dff_Zero.q ),
    .R(rst_n),
    .S(1'h1)
  );
  BUFX4 _168_ (
    .A(_054_[0]),
    .Y(Result[0])
  );
  BUFX4 _169_ (
    .A(_054_[1]),
    .Y(Result[1])
  );
  BUFX4 _170_ (
    .A(_054_[2]),
    .Y(Result[2])
  );
  BUFX4 _171_ (
    .A(_054_[3]),
    .Y(Result[3])
  );
  BUFX4 _172_ (
    .A(_055_),
    .Y(Zero)
  );
endmodule
